//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.InOrder = new HashSet<InOrder>();
        }
    
        public int ID_Book { get; set; }
        public string Name { get; set; }
        public int ID_Author { get; set; }
        public Nullable<int> ID_Jenre { get; set; }
        public int ID_Publisher { get; set; }
        public string Language { get; set; }
        public Nullable<int> NumberOfPages { get; set; }
        public double Price { get; set; }
        public string ISBN { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Jenre Jenre { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InOrder> InOrder { get; set; }
    }
}
