    //------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWcfService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author1", Namespace="http://schemas.datacontract.org/2004/07/myWcfService")]
    public partial class Author1 : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_AuthorField;
        
        private string SurnameField;
        
        private string NameField;
        
        private string SecondNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Author
        {
            get
            {
                return this.ID_AuthorField;
            }
            set
            {
                this.ID_AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName
        {
            get
            {
                return this.SecondNameField;
            }
            set
            {
                this.SecondNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowAuthors", ReplyAction="http://tempuri.org/IService1/ShowAuthorsResponse")]
    myWcfService.Author1[] ShowAuthors();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ShowAuthors", ReplyAction="http://tempuri.org/IService1/ShowAuthorsResponse")]
    System.Threading.Tasks.Task<myWcfService.Author1[]> ShowAuthorsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAuthor", ReplyAction="http://tempuri.org/IService1/DeleteAuthorResponse")]
    void DeleteAuthor(int i);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAuthor", ReplyAction="http://tempuri.org/IService1/DeleteAuthorResponse")]
    System.Threading.Tasks.Task DeleteAuthorAsync(int i);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertAuthor", ReplyAction="http://tempuri.org/IService1/InsertAuthorResponse")]
    void InsertAuthor(string Surname, string Name, string SecondName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertAuthor", ReplyAction="http://tempuri.org/IService1/InsertAuthorResponse")]
    System.Threading.Tasks.Task InsertAuthorAsync(string Surname, string Name, string SecondName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAuthor", ReplyAction="http://tempuri.org/IService1/UpdateAuthorResponse")]
    void UpdateAuthor(int ID_Author, string Surname, string Name, string SecondName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAuthor", ReplyAction="http://tempuri.org/IService1/UpdateAuthorResponse")]
    System.Threading.Tasks.Task UpdateAuthorAsync(int ID_Author, string Surname, string Name, string SecondName);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Author : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    public Service1Author()
    {
    }
    
    public Service1Author(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Author(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Author(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Author(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public myWcfService.Author1[] ShowAuthors()
    {
        return base.Channel.ShowAuthors();
    }
    
    public System.Threading.Tasks.Task<myWcfService.Author1[]> ShowAuthorsAsync()
    {
        return base.Channel.ShowAuthorsAsync();
    }
    
    public void DeleteAuthor(int i)
    {
        base.Channel.DeleteAuthor(i);
    }
    
    public System.Threading.Tasks.Task DeleteAuthorAsync(int i)
    {
        return base.Channel.DeleteAuthorAsync(i);
    }
    
    public void InsertAuthor(string Surname, string Name, string SecondName)
    {
        base.Channel.InsertAuthor(Surname, Name, SecondName);
    }
    
    public System.Threading.Tasks.Task InsertAuthorAsync(string Surname, string Name, string SecondName)
    {
        return base.Channel.InsertAuthorAsync(Surname, Name, SecondName);
    }
    
    public void UpdateAuthor(int ID_Author, string Surname, string Name, string SecondName)
    {
        base.Channel.UpdateAuthor(ID_Author, Surname, Name, SecondName);
    }
    
    public System.Threading.Tasks.Task UpdateAuthorAsync(int ID_Author, string Surname, string Name, string SecondName)
    {
        return base.Channel.UpdateAuthorAsync(ID_Author, Surname, Name, SecondName);
    }
}
