<?xml version="1.0" encoding="utf-8"?><Database Name="db_labs" Class="ClientDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-3VA95DI;Initial Catalog=db_labs;Integrated Security=True" SettingsObjectName="DataAccess.Properties.Settings" SettingsPropertyName="db_labsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="labs.client" Member="client">
    <Type Name="client">
      <Column Name="id_client" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="registration_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>