<?xml version="1.0" encoding="utf-8"?><Database Name="db_labs" Class="DeviceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-3VA95DI;Initial Catalog=db_labs;Integrated Security=True" SettingsObjectName="DataAccess.Properties.Settings" SettingsPropertyName="db_labsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="labs.device" Member="device">
    <Type Name="device">
      <Column Name="id_device" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="location" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>