//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public int id_device { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> category { get; set; }
        public int location { get; set; }
    }
}
